name: Java CI with Gradle

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up JDK
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # Options: 'temurin', 'zulu', 'adopt'
        java-version: '17'     # Adjust based on your project (e.g., 8, 11, 17)

    # Cache Gradle dependencies
    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: gradle-cache-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-cache-${{ runner.os }}-

    # Run Gradle Build
    - name: Build with Gradle
      run: ./gradlew build

    # Run Gradle Tests
    - name: Run Tests
      run: ./gradlew test
